project_id = "etvnmubdwhbwqkoxvevt"

[functions.send-email]
verify_jwt = false

[functions.generate-welcome-code]
verify_jwt = false

[functions.create-booking]
verify_jwt = false

[functions.send-booking-emails]
verify_jwt = false

[functions.send-reminders]
verify_jwt = false

[functions.create-upgrade]
verify_jwt = false

[functions.send-coupon-email]
verify_jwt = false
